// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllPatients() {
  return window['go']['excel']['ExcelService']['GetAllPatients']();
}

export function SavePatient(arg1) {
  return window['go']['excel']['ExcelService']['SavePatient'](arg1);
}
