// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {excel} from '../models';

export function GetAllPatients():Promise<Array<excel.Patient>>;

export function SavePatient(arg1:excel.Patient):Promise<void>;
